class Renderer{constructor(canvas){this._canvas=canvas;this._objects=[];this._clearColor={r:0.95,g:0.92,b:0.88,a:1.0};}
async init(){if(!navigator.gpu){throw Error("WebGPU is not supported in this browser.");}
const adapter=await navigator.gpu.requestAdapter();if(!adapter){throw Error("Couldn't request WebGPU adapter.");}
this._device=await adapter.requestDevice();this._context=this._canvas.getContext("webgpu");this._canvasFormat=navigator.gpu.getPreferredCanvasFormat();this._context.configure({device:this._device,format:this._canvasFormat,});this.resizeCanvas();window.addEventListener('resize',this.resizeCanvas.bind(this));}
resizeCanvas(){const devicePixelRatio=window.devicePixelRatio||1;const width=window.innerWidth*devicePixelRatio;const height=window.innerHeight*devicePixelRatio;this._canvas.width=width;this._canvas.height=height;this._canvas.style.width=`${window.innerWidth}px`;this._canvas.style.height=`${window.innerHeight}px`;this.render();}
async appendSceneObject(obj){await obj.init();this._objects.push(obj);}
renderToSelectedView(outputView){for(const obj of this._objects){obj?.updateGeometry();}
let encoder=this._device.createCommandEncoder();const pass=encoder.beginRenderPass({colorAttachments:[{view:outputView,clearValue:this._clearColor,loadOp:"clear",storeOp:"store",}]});for(const obj of this._objects){obj?.render(pass);}
pass.end();const computePass=encoder.beginComputePass();for(const obj of this._objects){obj?.compute(computePass);}
computePass.end();const commandBuffer=encoder.finish();this._device.queue.submit([commandBuffer]);}
render(){this.renderToSelectedView(this._context.getCurrentTexture().createView());}}
class RayTracer extends Renderer{constructor(canvas){super(canvas);this._tracer=null;}
async init(){if(!navigator.gpu){throw Error("WebGPU is not supported in this browser.");}
const adapter=await navigator.gpu.requestAdapter();if(!adapter){throw Error("Couldn't request WebGPU adapter.");}
this._device=await adapter.requestDevice();this._context=this._canvas.getContext("webgpu");this._canvasFormat="rgba8unorm";this._context.configure({device:this._device,format:this._canvasFormat,});this._shaderModule=this._device.createShaderModule({label:"Ray Tracer Shader",code:`
      @vertex
      fn vertexMain(@builtin(vertex_index) vIdx: u32) -> @builtin(position) vec4f {
        var pos = array<vec2f, 6>(
          vec2f(-1, -1), vec2f(1, -1), vec2f(-1, 1),
          vec2f(-1, 1), vec2f(1, -1), vec2f(1, 1)
        );
        return vec4f(pos[vIdx], 0, 1);
      }
      
      @group(0) @binding(0) var inTexture: texture_2d<f32>;
      @group(0) @binding(1) var inSampler: sampler;
      @group(0) @binding(2) var<uniform> imgSize: vec2f;
      
      @fragment
      fn fragmentMain(@builtin(position) fragCoord: vec4f) -> @location(0) vec4f {
        let uv = fragCoord.xy / imgSize; // vec2f(textureDimensions(inTexture, 0));
        return textureSample(inTexture, inSampler, uv);
      }
      `});this._outputSizeBuffer=this._device.createBuffer({label:"Ray Tracer output size buffer",size:8,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST,});this._pipeline=this._device.createRenderPipeline({label:"Ray Tracer Pipeline",layout:"auto",vertex:{module:this._shaderModule,entryPoint:"vertexMain",},fragment:{module:this._shaderModule,entryPoint:"fragmentMain",targets:[{format:this._canvasFormat}]}});this._sampler=this._device.createSampler({label:"Ray Tracer Sampler",magFilter:"linear",minFilter:"linear"});this.resizeCanvas();window.addEventListener('resize',this.resizeCanvas.bind(this));}
resizeCanvas(){const devicePixelRatio=window.devicePixelRatio||1;const width=window.innerWidth*devicePixelRatio;const height=window.innerHeight*devicePixelRatio;const ratio=width/height;const tgtHeight=height;let imgSize={width:tgtHeight*ratio,height:tgtHeight};this._offScreenTexture=this._device.createTexture({size:imgSize,format:this._canvasFormat,usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.STORAGE_BINDING,});if(this._tracer){this._tracer._imgWidth=this._offScreenTexture.width;this._tracer._imgHeight=this._offScreenTexture.height;this._tracer.updateGeometry();this._tracer.createBindGroup(this._offScreenTexture);}
this._bindGroup=this._device.createBindGroup({label:"Ray Tracer Renderer Bind Group",layout:this._pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:this._offScreenTexture.createView()},{binding:1,resource:this._sampler},{binding:2,resource:{buffer:this._outputSizeBuffer}}],});super.resizeCanvas();this._device.queue.writeBuffer(this._outputSizeBuffer,0,new Float32Array([width,height]));}
async setTracerObject(obj){await obj.init();obj._imgWidth=this._offScreenTexture.width;obj._imgHeight=this._offScreenTexture.height;obj.updateGeometry();this._tracer=obj;this._tracer.createBindGroup(this._offScreenTexture);}
render(){if(this._tracer){let encoder=this._device.createCommandEncoder();const computePass=encoder.beginComputePass();this._tracer.compute(computePass);computePass.end();this._device.queue.submit([encoder.finish()]);}
let encoder=this._device.createCommandEncoder();const pass=encoder.beginRenderPass({colorAttachments:[{view:this._context.getCurrentTexture().createView(),clearValue:this._clearColor,loadOp:"clear",storeOp:"store",}]});pass.setPipeline(this._pipeline);pass.setBindGroup(0,this._bindGroup);pass.draw(6);pass.end();this._device.queue.submit([encoder.finish()]);}};class SceneObject{static _objectCnt=0;constructor(device,canvasFormat,shaderFile){if(this.constructor==SceneObject){throw new Error("Abstract classes can't be instantiated.");}
this._device=device;this._canvasFormat=canvasFormat;this._shaderFile=shaderFile;SceneObject._objectCnt+=1;}
getName(){return this.constructor.name+" "+SceneObject._objectCnt.toString();}
async init(){await this.createGeometry();await this.createShaders();await this.createRenderPipeline();await this.createComputePipeline();}
async createGeometry(){throw new Error("Method 'createGeometry()' must be implemented.");}
updateGeometry(){}
loadShader(filename){return new Promise((resolve,reject)=>{const xhttp=new XMLHttpRequest();xhttp.open("GET",filename);xhttp.setRequestHeader("Cache-Control","no-cache, no-store, max-age=0");xhttp.onload=function(){if(xhttp.readyState===XMLHttpRequest.DONE&&xhttp.status===200){resolve(xhttp.responseText);}
else{reject({status:xhttp.status,statusText:xhttp.statusText});}};xhttp.onerror=function(){reject({status:xhttp.status,statusText:xhttp.statusText});};xhttp.send();});}
async createShaders(){let shaderCode=await this.loadShader(this._shaderFile);this._shaderModule=this._device.createShaderModule({label:" Shader "+this.getName(),code:shaderCode,});}
async createRenderPipeline(){throw new Error("Method 'createRenderPipeline()' must be implemented.");}
render(pass){throw new Error("Method 'render(pass)' must be implemented.");}
async createComputePipeline(){throw new Error("Method 'createComputePipeline()' must be implemented.");}
compute(pass){throw new Error("Method 'compute(pass)' must be implemented.");}}
class VolumeByteIO{constructor(){}
static readBinary(filename){return new Promise((resolve,reject)=>{const xhttp=new XMLHttpRequest();xhttp.open("GET",filename);xhttp.setRequestHeader("Cache-Control","no-cache, no-store, max-age=0");xhttp.responseType='arraybuffer';xhttp.onload=function(){if(xhttp.readyState===XMLHttpRequest.DONE&&xhttp.status===200){resolve(xhttp.response);}
else{reject(new Error('Error loading volume byte data: '+xhttp.status));}}
xhttp.onerror=function(){reject(new Error('Network error loading volume byte data'));}
xhttp.send();});}
static readBytes(view,offset,isLittle,type){switch(type){case'char':return[view.getInt8(offset,1)];break;case'uchar':return[view.getUint8(offset,1)];break;case'short':return[view.getInt16(offset,isLittle),2];break;case'ushort':return[view.getUint16(offset,isLittle),2];break;case'int':return[view.getInt32(offset,isLittle),4];break;case'uint':return[view.getUint32(offset,isLittle),4];break;case'float':return[view.getFloat32(offset,isLittle),4];break;case'double':return[view.getFloat64(offset,isLittle),8];break;}}
static async read(filename){let binarydata=await VolumeByteIO.readBinary(filename);let text=new TextDecoder().decode(binarydata);const dims=[181,217,181];const sizes=[1,1,1];const data=[];let offset=0;let view=new DataView(binarydata);for(let i=0;i<dims.reduce((s,val)=>s*val,1);++i){const[value,delta]=VolumeByteIO.readBytes(view,offset,true,'short');data.push(value);offset+=delta;}
return[dims,sizes,data];}
static isLittleEndian(){const buffer=new ArrayBuffer(2);const view=new DataView(buffer);view.setInt16(0,256,true);return view.getInt8(0)===0;}
static async write(volume,filename){const volumeData=new Uint8Array(volume.data.length*2);volume.data.forEach((value,index)=>{const view=new Uint16Array([value]);volumeData.set(new Uint8Array(view.buffer),index*2);});const blob=new Blob([volumeData],{type:'application/octet-stream'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='download.raws';a.click();URL.revokeObjectURL(a.href);}}
class VolumeData{constructor(filename){this._filename=filename;}
async init(){const[dims,sizes,data]=await VolumeByteIO.read(this._filename);this._dims=dims;this._sizes=sizes;this._data=data;}}
class VolumeRenderingObject extends SceneObject{constructor(device,canvasFormat,camera,volumeFile,shaderFile){super(device,canvasFormat,shaderFile);this._volume=new VolumeData(volumeFile);this._camera=camera;}
async createGeometry(){await this._volume.init();this._cameraBuffer=this._device.createBuffer({label:"Camera "+this.getName(),size:this._camera._pose.byteLength+this._camera._focal.byteLength+this._camera._resolutions.byteLength,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST,});this._device.queue.writeBuffer(this._cameraBuffer,0,this._camera._pose);this._device.queue.writeBuffer(this._cameraBuffer,this._camera._pose.byteLength,this._camera._focal);this._device.queue.writeBuffer(this._cameraBuffer,this._camera._pose.byteLength+this._camera._focal.byteLength,this._camera._resolutions);this._volumeBuffer=this._device.createBuffer({label:"Volume "+this.getName(),size:(this._volume._dims.length+this._volume._sizes.length+2)*Float32Array.BYTES_PER_ELEMENT,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST,});this._device.queue.writeBuffer(this._volumeBuffer,0,new Float32Array([...this._volume._dims,0,...this._volume._sizes,0]));this._dataBuffer=this._device.createBuffer({label:"Data "+this.getName(),size:this._volume._data.length*Float32Array.BYTES_PER_ELEMENT,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,});this._device.queue.writeBuffer(this._dataBuffer,0,new Float32Array(this._volume._data));}
updateGeometry(){this._camera.updateSize(this._imgWidth,this._imgHeight);this._device.queue.writeBuffer(this._cameraBuffer,this._camera._pose.byteLength+this._camera._focal.byteLength,this._camera._resolutions);}
updateCameraPose(){this._device.queue.writeBuffer(this._cameraBuffer,0,this._camera._pose);}
updateCameraFocal(){this._device.queue.writeBuffer(this._cameraBuffer,this._camera._pose.byteLength,this._camera._focal);}
async createShaders(){await super.createShaders();this._bindGroupLayout=this._device.createBindGroupLayout({label:"Ray Trace Volume Layout "+this.getName(),entries:[{binding:0,visibility:GPUShaderStage.COMPUTE,buffer:{}},{binding:1,visibility:GPUShaderStage.COMPUTE,buffer:{}},{binding:2,visibility:GPUShaderStage.COMPUTE,buffer:{type:"read-only-storage"}},{binding:3,visibility:GPUShaderStage.COMPUTE,storageTexture:{format:this._canvasFormat}}]});this._pipelineLayout=this._device.createPipelineLayout({label:"Ray Trace Volume Pipeline Layout",bindGroupLayouts:[this._bindGroupLayout],});}
async createRenderPipeline(){}
render(pass){}
async createComputePipeline(){this._computePipeline=this._device.createComputePipeline({label:"Ray Trace Volume Orthogonal Pipeline "+this.getName(),layout:this._pipelineLayout,compute:{module:this._shaderModule,entryPoint:"computeOrthogonalMain",}});this._computeProjectivePipeline=this._device.createComputePipeline({label:"Ray Trace Volume Projective Pipeline "+this.getName(),layout:this._pipelineLayout,compute:{module:this._shaderModule,entryPoint:"computeProjectiveMain",}});}
createBindGroup(outTexture){this._bindGroup=this._device.createBindGroup({label:"Ray Trace Volume Bind Group",layout:this._computePipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this._cameraBuffer}},{binding:1,resource:{buffer:this._volumeBuffer}},{binding:2,resource:{buffer:this._dataBuffer}},{binding:3,resource:outTexture.createView()}],});this._wgWidth=Math.ceil(outTexture.width);this._wgHeight=Math.ceil(outTexture.height);}
compute(pass){if(this._camera?._isProjective){pass.setPipeline(this._computeProjectivePipeline);}
else{pass.setPipeline(this._computePipeline);}
pass.setBindGroup(0,this._bindGroup);pass.dispatchWorkgroups(Math.ceil(this._wgWidth/16),Math.ceil(this._wgHeight/16));}};class PGA3D{static geometricProduct(a,b){return[a[0]*b[0]-a[1]*b[1]-a[2]*b[2]-a[3]*b[3]-a[7]*b[7]+a[11]*b[11]+a[12]*b[12]+a[13]*b[13],a[0]*b[1]+a[1]*b[0]-a[2]*b[3]+a[3]*b[2]+a[7]*b[13]+a[11]*b[12]-a[12]*b[11]+a[13]*b[7],a[0]*b[2]+a[1]*b[3]+a[2]*b[0]-a[3]*b[1]-a[7]*b[12]+a[11]*b[13]-a[12]*b[7]-a[13]*b[11],a[0]*b[3]-a[1]*b[2]+a[2]*b[1]+a[3]*b[0]+a[7]*b[11]+a[11]*b[7]+a[12]*b[13]-a[13]*b[12],a[0]*b[4]+a[1]*b[5]+a[2]*b[6]-a[3]*b[15]+a[4]*b[0]-a[5]*b[1]-a[6]*b[2]+a[7]*b[10]+a[8]*b[12]+a[9]*b[13]-a[10]*b[7]-a[11]*b[14]+a[12]*b[8]+a[13]*b[9]+a[14]*b[11]-a[15]*b[3],a[0]*b[5]-a[1]*b[4]+a[2]*b[15]+a[3]*b[6]+a[4]*b[1]+a[5]*b[0]-a[6]*b[3]-a[7]*b[9]-a[8]*b[11]+a[9]*b[7]+a[10]*b[12]-a[11]*b[8]-a[12]*b[14]+a[13]*b[10]+a[14]*b[12]+a[15]*b[2],a[0]*b[6]-a[1]*b[15]-a[2]*b[4]-a[3]*b[5]+a[4]*b[2]+a[5]*b[3]+a[6]*b[0]+a[7]*b[8]-a[8]*b[7]-a[9]*b[11]-a[10]*b[12]-a[11]*b[9]-a[12]*b[10]-a[13]*b[14]+a[14]*b[13]-a[15]*b[1],a[0]*b[7]+a[1]*b[13]-a[2]*b[12]+a[3]*b[11]+a[7]*b[0]+a[11]*b[3]-a[12]*b[2]+a[13]*b[1],a[0]*b[8]+a[1]*b[14]-a[2]*b[10]+a[3]*b[9]+a[4]*b[12]-a[5]*b[11]+a[6]*b[7]-a[7]*b[6]+a[8]*b[0]-a[9]*b[3]+a[10]*b[2]-a[11]*b[5]+a[12]*b[4]-a[13]*b[15]+a[14]*b[1]+a[15]*b[13],a[0]*b[9]+a[1]*b[10]+a[2]*b[14]-a[3]*b[8]+a[4]*b[13]-a[5]*b[7]-a[6]*b[11]+a[7]*b[5]+a[8]*b[3]+a[9]*b[0]-a[10]*b[1]-a[11]*b[6]+a[12]*b[15]+a[13]*b[4]+a[14]*b[2]-a[15]*b[12],a[0]*b[10]-a[1]*b[9]+a[2]*b[8]+a[3]*b[14]+a[4]*b[7]+a[5]*b[13]-a[6]*b[12]-a[7]*b[4]-a[8]*b[2]+a[9]*b[1]+a[10]*b[0]-a[11]*b[15]-a[12]*b[6]+a[13]*b[5]+a[14]*b[3]+a[15]*b[11],a[0]*b[11]+a[1]*b[12]+a[2]*b[13]-a[3]*b[7]-a[7]*b[3]+a[11]*b[0]-a[12]*b[1]-a[13]*b[2],a[0]*b[12]-a[1]*b[11]+a[2]*b[7]+a[3]*b[13]+a[7]*b[2]+a[11]*b[1]+a[12]*b[0]-a[13]*b[3],a[0]*b[13]-a[1]*b[7]-a[2]*b[11]-a[3]*b[12]-a[7]*b[1]+a[11]*b[2]+a[12]*b[3]+a[13]*b[0],a[0]*b[14]-a[1]*b[8]-a[2]*b[9]-a[3]*b[10]+a[4]*b[11]+a[5]*b[12]+a[6]*b[13]+a[7]*b[15]-a[8]*b[1]-a[9]*b[2]-a[10]*b[3]-a[11]*b[4]-a[12]*b[5]-a[13]*b[6]+a[14]*b[0]-a[15]*b[7],a[0]*b[15]+a[1]*b[6]-a[2]*b[5]+a[3]*b[4]+a[4]*b[3]-a[5]*b[2]+a[6]*b[1]-a[7]*b[14]+a[8]*b[13]-a[9]*b[12]+a[10]*b[11]-a[11]*b[10]+a[12]*b[9]-a[13]*b[8]+a[14]*b[7]+a[15]*b[0],];}
static reverse(a){return[a[0],-a[1],-a[2],-a[3],-a[4],-a[5],-a[6],-a[7],-a[8],-a[9],-a[10],a[11],a[12],a[13],a[14],a[15]];}
static applyMotor(p,m){return PGA3D.geometricProduct(m,PGA3D.geometricProduct(p,PGA3D.reverse(m)));}
static motorNorm(m){return Math.sqrt(m.map(val=>val*val).reduce((s,val)=>s+val,0));}
static createTranslator(dx,dy,dz){return[1,0,0,0,-dx/2,-dy/2,-dz/2,0,0,0,0,0,0,0,0,0];}
static extractTranslator(m){return[1,0,0,0,m[4],m[5],m[6],0,0,0,0,0,0,0,0,0];}
static createRotor(angle,dx=1,dy=0,dz=0,sx=0,sy=0,sz=0){let c=Math.cos(angle/2);let s=Math.sin(angle/2);let L=PGA3D.createLine(sx,sy,sz,dx,dy,dz);return[c,s*L[1],s*L[2],s*L[3],s*L[4],s*L[5],s*L[6],0,0,0,0,0,0,0,0,0];}
static extractRotor(m){return[m[0],m[1],m[2],m[3],0,0,0,0,0,0,0,0,0,0,0,0];}
static createDir(dx,dy,dz){return[0,dz,-dy,dx,0,0,0,0,0,0,0,0,0,0,0,0];}
static createLine(sx,sy,sz,dx,dy,dz){let n=PGA3D.createDir(dx,dy,dz);let dir=PGA3D.normalizeMotor(n);return[0,dir[1],dir[2],dir[3],-(-dir[2]*sz-dir[1]*sy),-(dir[1]*sx-dir[3]*sz),-(dir[3]*sy+dir[2]*sx),0,0,0,0,0,0,0,0,0];}
static createPoint(x,y,z){return[0,0,0,0,0,0,0,1,-z,y,-x,0,0,0,0,0];}
static extractPoint(p){return[-p[10]/p[7],p[9]/p[7],-p[8]/p[7]];}
static createPlane(nx,ny,nz,d){return[0,0,0,0,0,0,0,0,0,0,0,nx,ny,nz,-d,0];}
static createPlaneFromPoints(p1,p2,p3){let nx=(p2[1]*p3[2]-p3[1]*p2[2])-(p1[1]*p3[2]-p3[1]*p1[2])+(p1[1]*p2[2]-p2[1]*p1[2]);let ny=(p2[0]*p3[2]-p3[0]*p2[2])-(p1[0]*p3[2]-p3[0]*p1[2])+(p1[0]*p2[2]-p2[0]*p1[2]);let nz=(p2[0]*p3[1]-p3[0]*p2[1])-(p1[0]*p3[1]-p3[0]*p1[1])+(p1[0]*p2[1]-p2[0]*p1[1]);let d=(p1[0]*(p2[1]*p3[2]-p3[1]*p2[2])-p2[0]*(p1[1]*p3[2]-p3[1]*p1[2])+p3[0]*(p1[1]*p2[2]-p2[1]*p1[2]));return PGA3D.createPlane(nx,-ny,nz,d);}
static linePlaneIntersection(L,P){let new_p=PGA3D.geometricProduct(L,P);let isParallel=(Math.abs(new_p[7])<=0.00000001);let inPlane=isParallel&&(Math.abs(new_p[8])<=0.00000001)&&(Math.abs(new_p[9])<=0.00000001)&&(Math.abs(new_p[10])<=0.00000001);return[PGA3D.extractPoint(new_p),!isParallel,inPlane];}
static normalizeMotor(m){let mnorm=PGA3D.motorNorm(m);if(mnorm==0.0){return[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];}
return m.map(val=>val/mnorm);}
static applyMotorToPoint(p,m){let new_p=PGA3D.applyMotor(PGA3D.createPoint(p[0],p[1],p[2]),m);return PGA3D.extractPoint(new_p);};static applyMotorToDir(d,m){let r=PGA3D.extractRotor(m);let new_d=PGA3D.applyMotor(PGA3D.createPoint(d[0],d[1],d[2]),r);return PGA3D.extractPoint(new_d);}
static isInside(v0,v1,v2,p){let pga0=PGA3D.createPoint(v0[0],v0[1],v0[2]);let pga1=PGA3D.createPoint(v1[0],v1[1],v1[2]);let pga2=PGA3D.createPoint(v2[0],v2[1],v2[2]);let pgap=PGA3D.createPoint(p[0],p[1],p[2]);let plane012=PGA3D.createPlaneFromPoints(v0,v1,v2);let planep12=PGA3D.createPlaneFromPoints(p,v1,v2);let plane0p2=PGA3D.createPlaneFromPoints(v0,p,v2);let plane01p=PGA3D.createPlaneFromPoints(v0,v1,p);let area012=plane012[11]*plane012[11]+plane012[12]*plane012[12]+plane012[13]*plane012[13]+plane012[14]*plane012[14];let areap12=plane012[11]*planep12[11]+plane012[12]*planep12[12]+plane012[13]*planep12[13]+plane012[14]*planep12[14];let area0p2=plane012[11]*plane0p2[11]+plane012[12]*plane0p2[12]+plane012[13]*plane0p2[13]+plane012[14]*plane0p2[14];let area01p=plane012[11]*plane01p[11]+plane012[12]*plane01p[12]+plane012[13]*plane01p[13]+plane012[14]*plane01p[14];let lambda1=areap12/area012;let lambda2=area0p2/area012;let lambda3=area01p/area012;return lambda1>=0&&lambda1<=1&&lambda2>=0&&lambda2<=1&&lambda3>=0&&lambda3<=1;}}
class Camera{constructor(width,height){this._pose=new Float32Array(Array(16).fill(0));this._pose[0]=1;this._focal=new Float32Array(Array(2).fill(1));this._resolutions=new Float32Array([width,height]);}
resetPose(){this._pose[0]=1;for(let i=1;i<16;++i)this._pose[i]=0;this._focal[0]=1;this._focal[1]=1;}
updatePose(newpose){for(let i=0;i<16;++i)this._pose[i]=newpose[i];}
updateSize(width,height){this._resolutions[0]=width;this._resolutions[1]=height;}
moveX(d){let xAxis=PGA3D.applyMotorToDir([1,0,0],this._pose);let dt=PGA3D.createTranslator(d*xAxis[0],d*xAxis[1],d*xAxis[2]);let newpose=PGA3D.geometricProduct(dt,this._pose);this.updatePose(newpose);}
moveY(d){let yAxis=PGA3D.applyMotorToDir([0,1,0],this._pose);let dt=PGA3D.createTranslator(d*yAxis[0],d*yAxis[1],d*yAxis[2]);let newpose=PGA3D.geometricProduct(dt,this._pose);this.updatePose(newpose);}
moveZ(d){let zAxis=PGA3D.applyMotorToDir([0,0,1],this._pose);let dt=PGA3D.createTranslator(d*zAxis[0],d*zAxis[1],d*zAxis[2]);let newpose=PGA3D.geometricProduct(dt,this._pose);this.updatePose(newpose);}
rotateX(d){let xAxis=PGA3D.applyMotorToDir([1,0,0],this._pose);let camPos=PGA3D.applyMotorToPoint([0,0,0],this._pose);let dr=PGA3D.createRotor(d,xAxis[0],xAxis[1],xAxis[2],camPos[0],camPos[1],camPos[2]);let newpose=PGA3D.geometricProduct(dr,this._pose);this.updatePose(newpose);}
rotateY(d){let yAxis=PGA3D.applyMotorToDir([0,1,0],this._pose);let camPos=PGA3D.applyMotorToPoint([0,0,0],this._pose);let dr=PGA3D.createRotor(d,yAxis[0],yAxis[1],yAxis[2],camPos[0],camPos[1],camPos[2]);let newpose=PGA3D.geometricProduct(dr,this._pose);this.updatePose(newpose);}
rotateZ(d){let zAxis=PGA3D.applyMotorToDir([0,0,1],this._pose);let camPos=PGA3D.applyMotorToPoint([0,0,0],this._pose);let dr=PGA3D.createRotor(d,zAxis[0],zAxis[1],zAxis[2],camPos[0],camPos[1],camPos[2]);let newpose=PGA3D.geometricProduct(dr,this._pose);this.updatePose(newpose);}};;class PerlinNoise{constructor(){this.gradientPermutation();}
gradientPermutation(){this._permutation=Array.from({length:256},(_,i)=>i);for(let i=this._permutation.length-1;i>0;--i){const j=Math.floor(Math.random()*(i+1));[this._permutation[i],this._permutation[j]]=[this._permutation[j],this._permutation[i]];}}
gradient(hashvalue,x,y=0,z=0){switch(hashvalue&15){case 0:case 12:return x+y;case 1:case 13:return-x+y;case 2:case 14:return x-y;case 3:case 15:return-x-y;case 4:return x+z;case 5:return-x+z;case 6:return x-z;case 7:return-x-z;case 8:return y+z;case 9:return-y+z;case 10:return y-z;case 11:return-y-z;}}
noise1d(x){const fade=(t)=>{return t*t*t*(t*(t*6-15)+10)};const interpolate=(src,dst,t)=>{return src*t+dst*(1-t)};const ix=Math.floor(x)&255;const ixx=(ix+1)&255;x-=Math.floor(x);let t=fade(x);let src=this._permutation[ix];let dst=this._permutation[ixx];let srcGrad=this.gradient(src,x);let dstGrad=this.gradient(dst,x-1);return interpolate(srcGrad,dstGrad,t);}
noise2d(x,y){const fade=(t)=>{return t*t*t*(t*(t*6-15)+10)};const interpolate=(src,dst,t)=>{return src*t+dst*(1-t)};const ix=Math.floor(x)&255;const iy=Math.floor(y)&255;const ixx=(ix+1)&255;const iyy=(iy+1)&255;x-=Math.floor(x);y-=Math.floor(y);const u=fade(x);const v=fade(y);const aa=this._permutation[(this._permutation[ix]+iy)&255];const ba=this._permutation[(this._permutation[ixx]+iy)&255];const ab=this._permutation[(this._permutation[ix]+iyy)&255];const bb=this._permutation[(this._permutation[ixx]+iyy)&255];const aaGrad=this.gradient(aa,x,y);const baGrad=this.gradient(ba,x-1,y);const abGrad=this.gradient(ab,x,y-1);const bbGrad=this.gradient(bb,x-1,y-1);return interpolate(interpolate(aaGrad,baGrad,u),interpolate(abGrad,bbGrad,u),v);}
noise3d(x,y,z){const fade=(t)=>{return t*t*t*(t*(t*6-15)+10)};const interpolate=(src,dst,t)=>{return src*t+dst*(1-t)};const ix=Math.floor(x)&255;const iy=Math.floor(y)&255;const iz=Math.floor(z)&255;const ixx=(ix+1)&255;const iyy=(iy+1)&255;const izz=(iz+1)&255;x-=Math.floor(x);y-=Math.floor(y);z-=Math.floor(z);const u=fade(x);const v=fade(y);const w=fade(z);const aaa=this._permutation[(this._permutation[(this._permutation[ix]+iy)&255]+iz)&255];const baa=this._permutation[(this._permutation[(this._permutation[ixx]+iy)&255]+iz)&255];const aba=this._permutation[(this._permutation[(this._permutation[ix]+iyy)&255]+iz)&255];const bba=this._permutation[(this._permutation[(this._permutation[ixx]+iyy)&255]+iz)&255];const aab=this._permutation[(this._permutation[(this._permutation[ix]+iy)&255]+izz)&255];const bab=this._permutation[(this._permutation[(this._permutation[ixx]+iy)&255]+izz)&255];const abb=this._permutation[(this._permutation[(this._permutation[ix]+iyy)&255]+izz)&255];const bbb=this._permutation[(this._permutation[(this._permutation[ixx]+iyy)&255]+izz)&255];const aaaGrad=this.gradient(aaa,x,y,z);const baaGrad=this.gradient(baa,x-1,y,z);const abaGrad=this.gradient(aba,x,y-1,z);const bbaGrad=this.gradient(bba,x-1,y-1,z);const aabGrad=this.gradient(aab,x,y,z-1);const babGrad=this.gradient(bab,x-1,y,z-1);const abbGrad=this.gradient(abb,x,y-1,z-1);const bbbGrad=this.gradient(bbb,x-1,y-1,z-1);return interpolate(interpolate(interpolate(aaaGrad,baaGrad,u),interpolate(abaGrad,bbaGrad,u),v),interpolate(interpolate(aabGrad,babGrad,u),interpolate(abbGrad,bbbGrad,u),v),w);}
octaveNoise2d(x,y,freq=0.005,A=1,H=0.99,octaves=4,lacunarity=2){let total=0;let maxValue=0;let amplitude=A;let frequency=freq;for(let i=0;i<octaves;i++){total+=amplitude*this.noise2d(x*frequency,y*frequency);maxValue+=amplitude;frequency*=lacunarity;amplitude*=H;}
return maxValue>0?total/maxValue:0;}};const MODE_MIP=0;const MODE_DRR=1;const MODE_LINEAR=2;const MODE_PIECEWISE=3;const MODE_GRADIENT=4;const MODE_SPECTRAL=5;const MODE_WARMCOOL=6;const MODE_TERRAIN=7;const MODE_CLOUD=8;const MODE_FIRE=9;const MODE_SMOKE=10;const MODE_COMPOSED=11;class ProceduralSphereData{constructor(){this._dims=[64,64,64];this._sizes=[1.0,1.0,1.0];}
async init(){const[W,H,D]=this._dims;this._data=new Array(W*H*D).fill(0);for(let z=0;z<D;z++){for(let y=0;y<H;y++){for(let x=0;x<W;x++){const nx=(x/W)*2-1;const ny=(y/H)*2-1;const nz=(z/D)*2-1;const r=Math.sqrt(nx*nx+ny*ny+nz*nz);const sphere=Math.max(0,1-r/0.70);const torusR=0.50;const torusr=0.22;const dxz=Math.sqrt(nx*nx+nz*nz)-torusR;const torus=Math.max(0,1-Math.sqrt(dxz*dxz+ny*ny)/torusr);const density=Math.max(sphere,torus);this._data[z*W*H+y*W+x]=density*4095;}}}}}
class BiasedTerrainData{constructor(heightBias=0){this._dims=[128,64,128];this._sizes=[1.0,1.0,1.0];this._heightBias=heightBias;}
async init(){const pn=new PerlinNoise();const[W,H,D]=this._dims;this._data=new Array(W*H*D).fill(0);const waterY=Math.floor(0.38*H);for(let z=0;z<D;z++){for(let x=0;x<W;x++){const raw=pn.octaveNoise2d(x,z,0.015,1.0,0.5,6,2.0);const hRaw=Math.max(0,Math.min(1,(raw*2.5+1)*0.5));const h=Math.max(0,Math.min(1,hRaw+this._heightBias));const heightY=Math.max(1,Math.floor(h*H));let surfaceType;if(h<0.35)surfaceType=2;else if(h<0.42)surfaceType=2;else if(h<0.65)surfaceType=3;else if(h<0.78)surfaceType=4;else if(h<0.90)surfaceType=5;else surfaceType=6;for(let y=0;y<heightY&&y<H;y++){const idx=z*W*H+y*W+x;if(y===heightY-1){this._data[idx]=surfaceType;}else if(y>=heightY-3){this._data[idx]=(surfaceType===3)?4:(surfaceType===6?5:surfaceType);}else{const cv=pn.noise3d(x*0.09,y*0.07,z*0.09);this._data[idx]=(Math.abs(cv)<0.10&&h>=0.42)?0:5;}}
for(let y=heightY;y<waterY&&y<H;y++){this._data[z*W*H+y*W+x]=1;}}}}}
class CloudData{constructor(){this._dims=[64,64,64];this._sizes=[1.0,1.0,1.0];}
async init(){const pn=new PerlinNoise();const[W,H,D]=this._dims;this._data=new Array(W*H*D).fill(0);for(let z=0;z<D;z++){for(let y=0;y<H;y++){const heightFactor=y/H;if(heightFactor<0.30)continue;for(let x=0;x<W;x++){const n1=pn.octaveNoise2d(x,z,0.08,1.0,0.5,5,2.0)*0.5+0.5;const n2=pn.octaveNoise2d(x+100,z+100,0.15,0.5,0.5,4,2.0)*0.5+0.5;const vertFade=Math.sin(((heightFactor-0.30)/0.70)*Math.PI);const density=Math.max(0,(n1*0.7+n2*0.3)-0.40)*vertFade;this._data[z*W*H+y*W+x]=Math.min(4095,density*5500);}}}}}
class FireData{constructor(){this._dims=[64,64,64];this._sizes=[1.0,1.0,1.0];}
async init(){const pn=new PerlinNoise();const[W,H,D]=this._dims;this._data=new Array(W*H*D).fill(0);for(let z=0;z<D;z++){for(let y=0;y<H;y++){for(let x=0;x<W;x++){const nx=x/W,ny=y/H,nz=z/D;const heightFade=Math.pow(Math.max(0,1-ny),1.6);const cx=nx-0.5,cz=nz-0.5;const radial=Math.max(0,1-Math.sqrt(cx*cx+cz*cz)/0.40);const n1=Math.abs(pn.noise3d(x*0.15,y*0.12,z*0.15));const n2=Math.abs(pn.noise3d(x*0.30,y*0.25,z*0.30))*0.5;const density=(n1+n2)*radial*heightFade;this._data[z*W*H+y*W+x]=Math.min(4095,density*6500);}}}}}
class SmokeData{constructor(){this._dims=[64,64,64];this._sizes=[1.0,1.0,1.0];}
async init(){const pn=new PerlinNoise();const[W,H,D]=this._dims;this._data=new Array(W*H*D).fill(0);for(let z=0;z<D;z++){for(let y=0;y<H;y++){for(let x=0;x<W;x++){const nx=x/W,ny=y/H,nz=z/D;const heightFade=Math.sin(Math.min(ny*2.5,Math.PI));const spread=0.15+ny*0.35;const cx=nx-0.5,cz=nz-0.5;const radial=Math.max(0,1-Math.sqrt(cx*cx+cz*cz)/spread);const n1=pn.noise3d(x*0.10,y*0.08,z*0.10)*0.5+0.5;const n2=pn.noise3d(x*0.22,y*0.18,z*0.22)*0.25+0.25;const density=((n1+n2)/1.5)*radial*heightFade;this._data[z*W*H+y*W+x]=Math.min(4095,density*4095);}}}}}
class ComposedSceneData{constructor(){this._dims=[128,64,128];this._sizes=[1.0,1.0,1.0];}
async init(){const pn=new PerlinNoise();const[W,H,D]=this._dims;this._data=new Array(W*H*D).fill(0);const waterY=Math.floor(0.38*H*0.55);for(let z=0;z<D;z++){for(let x=0;x<W;x++){const raw=pn.octaveNoise2d(x,z,0.015,1.0,0.5,6,2.0);const h=Math.max(0,Math.min(1,(raw*2.5+1)*0.5));const heightY=Math.max(1,Math.floor(h*H*0.55));let surfaceType;if(h<0.35)surfaceType=2;else if(h<0.42)surfaceType=2;else if(h<0.65)surfaceType=3;else if(h<0.78)surfaceType=4;else if(h<0.90)surfaceType=5;else surfaceType=6;for(let y=0;y<heightY&&y<H;y++){const idx=z*W*H+y*W+x;this._data[idx]=(y===heightY-1)?surfaceType:5;}
for(let y=heightY;y<waterY&&y<H;y++){this._data[z*W*H+y*W+x]=1;}}}
const cloudBase=Math.floor(H*0.55);const cloudTop=Math.floor(H*0.90);for(let z=0;z<D;z++){for(let y=cloudBase;y<cloudTop;y++){const t=(y-cloudBase)/(cloudTop-cloudBase);const vertFade=Math.sin(t*Math.PI);for(let x=0;x<W;x++){const n=pn.octaveNoise2d(x,z,0.08,1.0,0.5,4,2.0)*0.5+0.5;const density=Math.max(0,n-0.40)*vertFade;if(density>0.04){this._data[z*W*H+y*W+x]=100+density*100;}}}}}}
const SCENE_CAMERA_DEFAULTS={volume:{isProjective:false,focal:1.0,actions:[]},terrain:{isProjective:true,focal:2.0,actions:[{type:'rotateX',angle:-Math.PI/5},{type:'moveZ',dist:-1.4},{type:'moveY',dist:0.3},]},effect:{isProjective:true,focal:1.5,actions:[{type:'rotateX',angle:-Math.PI/8},{type:'moveZ',dist:-1.2},]},composed:{isProjective:true,focal:2.0,actions:[{type:'rotateX',angle:-Math.PI/5},{type:'moveZ',dist:-1.6},{type:'moveY',dist:0.4},]},};const SCENES=[{name:'Brain T1 — MIP (Orthographic)',datasetIdx:0,modeIdx:MODE_MIP,camType:'volume'},{name:'Brain T1 — MIP (Projective/Pinhole)',datasetIdx:0,modeIdx:MODE_MIP,camType:'volume'},{name:'Brain PD — DRR  [Custom Loader]',datasetIdx:1,modeIdx:MODE_DRR,camType:'volume'},{name:'Procedural Sphere+Torus — Linear TF',datasetIdx:2,modeIdx:MODE_LINEAR,camType:'volume'},{name:'Brain T1 — Linear Transfer Function',datasetIdx:0,modeIdx:MODE_LINEAR,camType:'volume'},{name:'Brain T1 — Piecewise Linear TF',datasetIdx:0,modeIdx:MODE_PIECEWISE,camType:'volume'},{name:'Brain T1 — Gradient (Edge) TF',datasetIdx:0,modeIdx:MODE_GRADIENT,camType:'volume'},{name:'Brain T1 — Spectral (Rainbow) TF',datasetIdx:0,modeIdx:MODE_SPECTRAL,camType:'volume'},{name:'Brain T1 — Warm-Cool Cinematic TF',datasetIdx:0,modeIdx:MODE_WARMCOOL,camType:'volume'},{name:'Terrain — Grass Plains',datasetIdx:3,modeIdx:MODE_TERRAIN,camType:'terrain'},{name:'Terrain — Snow Peaks (Arctic)',datasetIdx:4,modeIdx:MODE_TERRAIN,camType:'terrain'},{name:'Terrain — Ocean World (Water)',datasetIdx:5,modeIdx:MODE_TERRAIN,camType:'terrain'},{name:'Terrain — Dirt/Rock Highlands',datasetIdx:6,modeIdx:MODE_TERRAIN,camType:'terrain'},{name:'Effect — Volumetric Clouds',datasetIdx:7,modeIdx:MODE_CLOUD,camType:'effect'},{name:'Effect — Volumetric Fire',datasetIdx:8,modeIdx:MODE_FIRE,camType:'effect'},{name:'Effect — Volumetric Smoke',datasetIdx:9,modeIdx:MODE_SMOKE,camType:'effect'},{name:'3D Scene — Terrain + Cloud Layer',datasetIdx:10,modeIdx:MODE_COMPOSED,camType:'composed'},];class Project7Object extends VolumeRenderingObject{constructor(device,canvasFormat,camera,shaderFile){super(device,canvasFormat,camera,null,shaderFile);this._activeScene=0;this._bindGroups=[];}
async createGeometry(){const brainT1=new VolumeData('/assets/brainweb-t1-1mm-pn0-rf0.raws');const brainPD=new VolumeData('/assets/brainweb-pd-1mm-pn0-rf0.raws');await Promise.all([brainT1.init(),brainPD.init()]);const sphere=new ProceduralSphereData();const grass=new BiasedTerrainData(0.00);const snow=new BiasedTerrainData(0.28);const water=new BiasedTerrainData(-0.28);const dirt=new BiasedTerrainData(0.15);const cloud=new CloudData();const fire=new FireData();const smoke=new SmokeData();const composed=new ComposedSceneData();await Promise.all([sphere.init(),grass.init(),snow.init(),water.init(),dirt.init(),cloud.init(),fire.init(),smoke.init(),composed.init()]);this._datasets=[brainT1,brainPD,sphere,grass,snow,water,dirt,cloud,fire,smoke,composed];this._cameraBuffer=this._device.createBuffer({label:'Project7 Camera',size:this._camera._pose.byteLength
+this._camera._focal.byteLength
+this._camera._resolutions.byteLength,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST,});this._device.queue.writeBuffer(this._cameraBuffer,0,this._camera._pose);this._device.queue.writeBuffer(this._cameraBuffer,this._camera._pose.byteLength,this._camera._focal);this._device.queue.writeBuffer(this._cameraBuffer,this._camera._pose.byteLength+this._camera._focal.byteLength,this._camera._resolutions);this._volInfoBuffers=[];this._dataBuffers=[];for(const ds of this._datasets){const vib=this._device.createBuffer({size:8*Float32Array.BYTES_PER_ELEMENT,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST,});this._device.queue.writeBuffer(vib,0,new Float32Array([...ds._dims,0,...ds._sizes,0]));const dBuf=this._device.createBuffer({size:ds._data.length*Float32Array.BYTES_PER_ELEMENT,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,});this._device.queue.writeBuffer(dBuf,0,new Float32Array(ds._data));this._volInfoBuffers.push(vib);this._dataBuffers.push(dBuf);}
this._volumeBuffer=this._volInfoBuffers[0];this._dataBuffer=this._dataBuffers[0];}
async createComputePipeline(){const make=(entry)=>this._device.createComputePipeline({label:`P7 ${entry}`,layout:this._pipelineLayout,compute:{module:this._shaderModule,entryPoint:entry},});this._pipelines=[[make('computeOrthogonalMIPMain'),make('computeProjectiveMIPMain')],[make('computeOrthogonalDRRMain'),make('computeProjectiveDRRMain')],[make('computeOrthogonalLinearTFMain'),make('computeProjectiveLinearTFMain')],[make('computeOrthogonalPiecewiseMain'),make('computeProjectivePiecewiseMain')],[make('computeOrthogonalGradientMain'),make('computeProjectiveGradientMain')],[make('computeOrthogonalSpectralMain'),make('computeProjectiveSpectralMain')],[make('computeOrthogonalWarmCoolMain'),make('computeProjectiveWarmCoolMain')],[make('computeOrthogonalTerrainMain'),make('computeProjectiveTerrainMain')],[make('computeOrthogonalCloudMain'),make('computeProjectiveCloudMain')],[make('computeOrthogonalFireMain'),make('computeProjectiveFireMain')],[make('computeOrthogonalSmokeMain'),make('computeProjectiveSmokeMain')],[make('computeOrthogonalComposedMain'),make('computeProjectiveComposedMain')],];this._computePipeline=this._pipelines[0][0];this._computeProjectivePipeline=this._pipelines[0][1];}
createBindGroup(outTexture){const layout=this._pipelines[0][0].getBindGroupLayout(0);this._bindGroups=this._datasets.map((_,i)=>this._device.createBindGroup({label:`P7 BindGroup ds=${i}`,layout,entries:[{binding:0,resource:{buffer:this._cameraBuffer}},{binding:1,resource:{buffer:this._volInfoBuffers[i]}},{binding:2,resource:{buffer:this._dataBuffers[i]}},{binding:3,resource:outTexture.createView()},],}));this._wgWidth=outTexture.width;this._wgHeight=outTexture.height;}
compute(pass){const scene=SCENES[this._activeScene];const camIdx=this._camera._isProjective?1:0;const pipeline=this._pipelines[scene.modeIdx][camIdx];pass.setPipeline(pipeline);pass.setBindGroup(0,this._bindGroups[scene.datasetIdx]);pass.dispatchWorkgroups(Math.ceil(this._wgWidth/16),Math.ceil(this._wgHeight/16));}
updateCameraPose(){this._device.queue.writeBuffer(this._cameraBuffer,0,this._camera._pose);}
updateCameraFocal(){this._device.queue.writeBuffer(this._cameraBuffer,this._camera._pose.byteLength,this._camera._focal);}
updateGeometry(){this._camera.updateSize(this._imgWidth,this._imgHeight);this._device.queue.writeBuffer(this._cameraBuffer,this._camera._pose.byteLength+this._camera._focal.byteLength,this._camera._resolutions);}}
function buildHUD(){const overlayStyle=document.createElement('style');overlayStyle.textContent=`
    #loading-overlay {
      position: fixed; inset: 0; display: flex; align-items: center;
      justify-content: center; background: #000;
      color: #7af; font: bold 20px 'Courier New', monospace;
      z-index: 200; transition: opacity 0.5s;
    }
  `;document.head.appendChild(overlayStyle);const overlay=document.createElement('div');overlay.id='loading-overlay';overlay.textContent='⏳  Generating volumes… please wait';document.body.appendChild(overlay);function addKey(parent,label){const btn=document.createElement('span');btn.className='hud-button';btn.textContent=label;parent.appendChild(btn);}
function addRow(parent,labelText,keys,liveEl){const row=document.createElement('div');row.className='hud-control-row';const lbl=document.createElement('span');lbl.className='hud-label';lbl.textContent=labelText;row.appendChild(lbl);for(const k of keys){addKey(row,k);}
if(liveEl){row.appendChild(liveEl);}
parent.appendChild(row);}
function addSection(hud,title){const sec=document.createElement('div');sec.className='hud-section';const hdr=document.createElement('div');hdr.className='hud-section-header';hdr.textContent=title;sec.appendChild(hdr);hud.appendChild(sec);return sec;}
const hud=document.createElement('div');hud.id='hud';const titleEl=document.createElement('div');titleEl.className='hud-title';titleEl.textContent='Project 7 — Volume Rendering';hud.appendChild(titleEl);const sceneSec=addSection(hud,'SCENE NAVIGATION');addRow(sceneSec,'Next / Prev Scene',['Tab','Shift+Tab']);addRow(sceneSec,'Jump to Scene',['1','2','3','4','5','6','7','8','9','0']);const hudSceneEl=document.createElement('span');hudSceneEl.id='scene-name';hudSceneEl.className='hud-value hud-value--truncated';addRow(sceneSec,'Active Scene',[],hudSceneEl);const camSec=addSection(hud,'CAMERA');const hudCamModeEl=document.createElement('span');hudCamModeEl.id='cam-mode';hudCamModeEl.className='hud-value';addRow(camSec,'Toggle Ortho / Projective',['P'],hudCamModeEl);const hudFocalEl=document.createElement('span');hudFocalEl.id='focal-val';hudFocalEl.className='hud-value';addRow(camSec,'Focal Length',['+','-'],hudFocalEl);addRow(camSec,'Reset Camera',['R']);const movSec=addSection(hud,'CAMERA MOVEMENT');addRow(movSec,'Move Forward / Back',['W','S']);addRow(movSec,'Move Left / Right',['A','D']);addRow(movSec,'Move Up / Down',['Q','E']);const rotSec=addSection(hud,'CAMERA ROTATION');addRow(rotSec,'Pitch (X-axis)',['↑','↓']);addRow(rotSec,'Yaw (Y-axis)',['←','→']);addRow(rotSec,'Roll (Z-axis)',['Z','X']);const info=document.createElement('div');info.className='hud-info';info.textContent='H — Hide / Show HUD';hud.appendChild(info);document.body.appendChild(hud);const showBtn=document.createElement('button');showBtn.id='show-hud-toggle';showBtn.textContent='Show HUD';showBtn.addEventListener('click',()=>{hud.style.display='';showBtn.style.display='none';});document.body.appendChild(showBtn);return{overlay,hud,showBtn};}
function updateHUD(sceneIdx,camera){const nameEl=document.getElementById('scene-name');const camEl=document.getElementById('cam-mode');const focalEl=document.getElementById('focal-val');if(nameEl)nameEl.textContent=`Scene ${sceneIdx + 1} / ${SCENES.length}: ${SCENES[sceneIdx].name}`;if(camEl)camEl.textContent=camera._isProjective?'Projective':'Orthographic';if(focalEl)focalEl.textContent=camera._isProjective?camera._focal[0].toFixed(2):'—';}
function resetCamera(camera,sceneIdx){const camType=SCENES[sceneIdx].camType;const cfg=SCENE_CAMERA_DEFAULTS[camType]||SCENE_CAMERA_DEFAULTS.volume;camera.resetPose();camera._isProjective=cfg.isProjective;const f=cfg.focal??1.0;camera._focal[0]=f;camera._focal[1]=f;for(const act of(cfg.actions||[])){if(act.type==='rotateX')camera.rotateX(act.angle);if(act.type==='moveZ')camera.moveZ(act.dist);if(act.type==='moveY')camera.moveY(act.dist);}}
async function main(){const canvas=document.createElement('canvas');canvas.id='renderCanvas';document.body.appendChild(canvas);const{overlay,hud,showBtn}=buildHUD();const renderer=new RayTracer(canvas);await renderer.init();const camera=new Camera();resetCamera(camera,0);const volObj=new Project7Object(renderer._device,renderer._canvasFormat,camera,'//optimized_project_7_vol.wgsl');updateHUD(0,camera);await renderer.setTracerObject(volObj);volObj._activeScene=0;overlay.style.opacity='0';setTimeout(()=>overlay.remove(),600);function switchScene(idx){const n=SCENES.length;idx=((idx%n)+n)%n;volObj._activeScene=idx;resetCamera(camera,idx);if(idx===1)camera._isProjective=true;volObj.updateCameraPose();volObj.updateCameraFocal();updateHUD(idx,camera);}
const MOVE_STEP=0.04;const ROT_STEP=0.035;const FOCAL_STEP=0.05;const keys=new Set();window.addEventListener('keydown',(e)=>{keys.add(e.key);switch(e.key){case'Tab':e.preventDefault();switchScene(volObj._activeScene+(e.shiftKey?-1:1));break;case'1':switchScene(0);break;case'2':switchScene(1);break;case'3':switchScene(2);break;case'4':switchScene(3);break;case'5':switchScene(4);break;case'6':switchScene(5);break;case'7':switchScene(6);break;case'8':switchScene(7);break;case'9':switchScene(8);break;case'0':switchScene(9);break;case'p':case'P':camera._isProjective=!camera._isProjective;updateHUD(volObj._activeScene,camera);break;case'+':case'=':camera._focal[0]=Math.min(10.0,camera._focal[0]+FOCAL_STEP);camera._focal[1]=Math.min(10.0,camera._focal[1]+FOCAL_STEP);volObj.updateCameraFocal();updateHUD(volObj._activeScene,camera);break;case'-':case'_':camera._focal[0]=Math.max(0.2,camera._focal[0]-FOCAL_STEP);camera._focal[1]=Math.max(0.2,camera._focal[1]-FOCAL_STEP);volObj.updateCameraFocal();updateHUD(volObj._activeScene,camera);break;case'r':case'R':resetCamera(camera,volObj._activeScene);if(volObj._activeScene===1)camera._isProjective=true;volObj.updateCameraPose();volObj.updateCameraFocal();updateHUD(volObj._activeScene,camera);break;case'h':case'H':if(hud.style.display==='none'){hud.style.display='';showBtn.style.display='none';}else{hud.style.display='none';showBtn.style.display='';}
break;}});window.addEventListener('keyup',(e)=>keys.delete(e.key));function processKeys(){let moved=false;if(keys.has('w')||keys.has('W')){camera.moveZ(MOVE_STEP);moved=true;}
if(keys.has('s')||keys.has('S')){camera.moveZ(-MOVE_STEP);moved=true;}
if(keys.has('a')||keys.has('A')){camera.moveX(-MOVE_STEP);moved=true;}
if(keys.has('d')||keys.has('D')){camera.moveX(MOVE_STEP);moved=true;}
if(keys.has('q')||keys.has('Q')){camera.moveY(MOVE_STEP);moved=true;}
if(keys.has('e')||keys.has('E')){camera.moveY(-MOVE_STEP);moved=true;}
if(keys.has('ArrowUp')){camera.rotateX(-ROT_STEP);moved=true;}
if(keys.has('ArrowDown')){camera.rotateX(ROT_STEP);moved=true;}
if(keys.has('ArrowLeft')){camera.rotateY(-ROT_STEP);moved=true;}
if(keys.has('ArrowRight')){camera.rotateY(ROT_STEP);moved=true;}
if(keys.has('z')||keys.has('Z')){camera.rotateZ(-ROT_STEP);moved=true;}
if(keys.has('x')||keys.has('X')){camera.rotateZ(ROT_STEP);moved=true;}
if(moved)volObj.updateCameraPose();}
function frame(){processKeys();renderer.render();requestAnimationFrame(frame);}
requestAnimationFrame(frame);}
main().catch((err)=>{const p=document.createElement('p');p.style.cssText='color:#f88;font:16px monospace;padding:20px;';p.innerHTML=`<b>Error:</b> ${err.message}<br>${navigator.userAgent}`;document.body.appendChild(p);});