class Renderer{constructor(canvas){this._canvas=canvas;this._objects=[];this._clearColor={r:0.95,g:0.92,b:0.88,a:1.0};}
async init(){if(!navigator.gpu){throw Error("WebGPU is not supported in this browser.");}
const adapter=await navigator.gpu.requestAdapter();if(!adapter){throw Error("Couldn't request WebGPU adapter.");}
this._device=await adapter.requestDevice();this._context=this._canvas.getContext("webgpu");this._canvasFormat=navigator.gpu.getPreferredCanvasFormat();this._context.configure({device:this._device,format:this._canvasFormat,});this.resizeCanvas();window.addEventListener('resize',this.resizeCanvas.bind(this));}
resizeCanvas(){const devicePixelRatio=window.devicePixelRatio||1;const width=window.innerWidth*devicePixelRatio;const height=window.innerHeight*devicePixelRatio;this._canvas.width=width;this._canvas.height=height;this._canvas.style.width=`${window.innerWidth}px`;this._canvas.style.height=`${window.innerHeight}px`;this.render();}
async appendSceneObject(obj){await obj.init();this._objects.push(obj);}
renderToSelectedView(outputView){for(const obj of this._objects){obj?.updateGeometry();}
let encoder=this._device.createCommandEncoder();const pass=encoder.beginRenderPass({colorAttachments:[{view:outputView,clearValue:this._clearColor,loadOp:"clear",storeOp:"store",}]});for(const obj of this._objects){obj?.render(pass);}
pass.end();const computePass=encoder.beginComputePass();for(const obj of this._objects){obj?.compute(computePass);}
computePass.end();const commandBuffer=encoder.finish();this._device.queue.submit([commandBuffer]);}
render(){this.renderToSelectedView(this._context.getCurrentTexture().createView());}}
class SceneObject{static _objectCnt=0;constructor(device,canvasFormat,shaderFile){if(this.constructor==SceneObject){throw new Error("Abstract classes can't be instantiated.");}
this._device=device;this._canvasFormat=canvasFormat;this._shaderFile=shaderFile;SceneObject._objectCnt+=1;}
getName(){return this.constructor.name+" "+SceneObject._objectCnt.toString();}
async init(){await this.createGeometry();await this.createShaders();await this.createRenderPipeline();await this.createComputePipeline();}
async createGeometry(){throw new Error("Method 'createGeometry()' must be implemented.");}
updateGeometry(){}
loadShader(filename){return new Promise((resolve,reject)=>{const xhttp=new XMLHttpRequest();xhttp.open("GET",filename);xhttp.setRequestHeader("Cache-Control","no-cache, no-store, max-age=0");xhttp.onload=function(){if(xhttp.readyState===XMLHttpRequest.DONE&&xhttp.status===200){resolve(xhttp.responseText);}
else{reject({status:xhttp.status,statusText:xhttp.statusText});}};xhttp.onerror=function(){reject({status:xhttp.status,statusText:xhttp.statusText});};xhttp.send();});}
async createShaders(){let shaderCode=await this.loadShader(this._shaderFile);this._shaderModule=this._device.createShaderModule({label:" Shader "+this.getName(),code:shaderCode,});}
async createRenderPipeline(){throw new Error("Method 'createRenderPipeline()' must be implemented.");}
render(pass){throw new Error("Method 'render(pass)' must be implemented.");}
async createComputePipeline(){throw new Error("Method 'createComputePipeline()' must be implemented.");}
compute(pass){throw new Error("Method 'compute(pass)' must be implemented.");}}
class FireworksSystemObject extends SceneObject{constructor(device,canvasFormat,shaderFile,numParticles=10000){super(device,canvasFormat,shaderFile);this._numParticles=numParticles;this._step=0;this._uniformsArray=new Float32Array([0.0,0.0,0.0,0.0]);}
setEmitter(x,y){this._uniformsArray[0]=x;this._uniformsArray[1]=y;}
async createGeometry(){this._particles=new Float32Array(this._numParticles*12);this._particleBuffers=[this._device.createBuffer({label:'Fireworks Buffer 0 '+this.getName(),size:this._particles.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,}),this._device.createBuffer({label:'Fireworks Buffer 1 '+this.getName(),size:this._particles.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,}),];this._uniformsBuffer=this._device.createBuffer({label:'Fireworks Uniforms '+this.getName(),size:this._uniformsArray.byteLength,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST,});this._spriteTexture=this._createSpriteTexture();this._spriteSampler=this._device.createSampler({magFilter:'linear',minFilter:'linear',});this._step=0;this._resetParticles();}
updateGeometry(){}
async createShaders(){await super.createShaders();this._bindGroupLayout=this._device.createBindGroupLayout({label:'Fireworks BGL '+this.getName(),entries:[{binding:0,visibility:GPUShaderStage.VERTEX|GPUShaderStage.COMPUTE,buffer:{type:'read-only-storage'},},{binding:1,visibility:GPUShaderStage.COMPUTE,buffer:{type:'storage'},},{binding:2,visibility:GPUShaderStage.COMPUTE,buffer:{type:'uniform'},},{binding:3,visibility:GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,texture:{},},{binding:4,visibility:GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,sampler:{},},],});this._pipelineLayout=this._device.createPipelineLayout({label:'Fireworks Pipeline Layout '+this.getName(),bindGroupLayouts:[this._bindGroupLayout],});}
async createRenderPipeline(){this._renderPipeline=this._device.createRenderPipeline({label:'Fireworks Render Pipeline '+this.getName(),layout:this._pipelineLayout,vertex:{module:this._shaderModule,entryPoint:'vertexMain',},fragment:{module:this._shaderModule,entryPoint:'fragmentMain',targets:[{format:this._canvasFormat,blend:{color:{srcFactor:'src-alpha',dstFactor:'one',operation:'add'},alpha:{srcFactor:'one',dstFactor:'one',operation:'add'},},}],},primitive:{topology:'triangle-list'},});this._bindGroups=this._createBindGroups(this._renderPipeline);}
async createComputePipeline(){this._computePipeline=this._device.createComputePipeline({label:'Fireworks Compute Pipeline '+this.getName(),layout:this._pipelineLayout,compute:{module:this._shaderModule,entryPoint:'computeMain'},});}
render(pass){pass.setPipeline(this._renderPipeline);pass.setBindGroup(0,this._bindGroups[this._step%2]);pass.draw(6,this._numParticles);}
compute(pass){this._uniformsArray[2]=performance.now()/1000.0;this._device.queue.writeBuffer(this._uniformsBuffer,0,this._uniformsArray);pass.setPipeline(this._computePipeline);pass.setBindGroup(0,this._bindGroups[this._step%2]);pass.dispatchWorkgroups(Math.ceil(this._numParticles/256));++this._step;}
_resetParticles(){const colors=[[1.0,0.15,0.05],[1.0,0.55,0.05],[1.0,1.00,0.20],[0.40,0.80,1.0],[0.90,0.40,1.0],];for(let i=0;i<this._numParticles;i++){const base=i*12;this._particles[base+0]=0.0;this._particles[base+1]=0.0;const angle=Math.random()*Math.PI*2;const speed=0.004+Math.random()*0.018;this._particles[base+2]=Math.cos(angle)*speed;this._particles[base+3]=Math.sin(angle)*speed;const c=colors[Math.floor(Math.random()*colors.length)];this._particles[base+4]=c[0];this._particles[base+5]=c[1];this._particles[base+6]=c[2];this._particles[base+7]=1.0;const maxLife=80+Math.random()*120;this._particles[base+8]=maxLife*Math.random();this._particles[base+9]=maxLife;this._particles[base+10]=0.0;this._particles[base+11]=0.0;}
this._device.queue.writeBuffer(this._particleBuffers[0],0,this._particles);}
_createSpriteTexture(){const size=64;const half=size/2;const data=new Uint8Array(size*size*4);for(let y=0;y<size;y++){for(let x=0;x<size;x++){const dx=x-half,dy=y-half;const dist=Math.sqrt(dx*dx+dy*dy)/half;const alpha=Math.max(0,1.0-dist*dist);const i=(y*size+x)*4;data[i+0]=255;data[i+1]=255;data[i+2]=255;data[i+3]=Math.round(alpha*255);}}
const texture=this._device.createTexture({size:[size,size,1],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST,});this._device.queue.writeTexture({texture},data,{bytesPerRow:size*4},[size,size],);return texture;}
_createBindGroups(pipeline){return[0,1].map(i=>this._device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this._particleBuffers[i]}},{binding:1,resource:{buffer:this._particleBuffers[1-i]}},{binding:2,resource:{buffer:this._uniformsBuffer}},{binding:3,resource:this._spriteTexture.createView()},{binding:4,resource:this._spriteSampler},],}));}}
class NebulaSystemObject extends SceneObject{constructor(device,canvasFormat,shaderFile,numParticles=10000){super(device,canvasFormat,shaderFile);this._numParticles=numParticles;this._step=0;this._uniformsArray=new Float32Array([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]);}
setWind(x,y){this._uniformsArray[0]=x;this._uniformsArray[1]=y;}
setMousePos(x,y){this._uniformsArray[2]=x;this._uniformsArray[3]=y;}
setAttract(v){this._uniformsArray[4]=v;}
async createGeometry(){this._particles=new Float32Array(this._numParticles*8);this._particleBuffers=[this._device.createBuffer({label:'Nebula Buffer 0 '+this.getName(),size:this._particles.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,}),this._device.createBuffer({label:'Nebula Buffer 1 '+this.getName(),size:this._particles.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,}),];this._uniformsBuffer=this._device.createBuffer({label:'Nebula Uniforms '+this.getName(),size:this._uniformsArray.byteLength,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST,});this._spriteTexture=this._createSpriteTexture();this._spriteSampler=this._device.createSampler({magFilter:'linear',minFilter:'linear',});this._step=0;this._resetParticles();}
updateGeometry(){}
async createShaders(){await super.createShaders();this._bindGroupLayout=this._device.createBindGroupLayout({label:'Nebula BGL '+this.getName(),entries:[{binding:0,visibility:GPUShaderStage.VERTEX|GPUShaderStage.COMPUTE,buffer:{type:'read-only-storage'},},{binding:1,visibility:GPUShaderStage.COMPUTE,buffer:{type:'storage'},},{binding:2,visibility:GPUShaderStage.COMPUTE,buffer:{type:'uniform'},},{binding:3,visibility:GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,texture:{},},{binding:4,visibility:GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,sampler:{},},],});this._pipelineLayout=this._device.createPipelineLayout({label:'Nebula Pipeline Layout '+this.getName(),bindGroupLayouts:[this._bindGroupLayout],});}
async createRenderPipeline(){this._renderPipeline=this._device.createRenderPipeline({label:'Nebula Render Pipeline '+this.getName(),layout:this._pipelineLayout,vertex:{module:this._shaderModule,entryPoint:'vertexMain',},fragment:{module:this._shaderModule,entryPoint:'fragmentMain',targets:[{format:this._canvasFormat,blend:{color:{srcFactor:'src-alpha',dstFactor:'one',operation:'add'},alpha:{srcFactor:'one',dstFactor:'one',operation:'add'},},}],},primitive:{topology:'triangle-list'},});this._bindGroups=this._createBindGroups(this._renderPipeline);}
async createComputePipeline(){this._computePipeline=this._device.createComputePipeline({label:'Nebula Compute Pipeline '+this.getName(),layout:this._pipelineLayout,compute:{module:this._shaderModule,entryPoint:'computeMain'},});}
render(pass){pass.setPipeline(this._renderPipeline);pass.setBindGroup(0,this._bindGroups[this._step%2]);pass.draw(6,this._numParticles);}
compute(pass){this._uniformsArray[5]=performance.now()/1000.0;this._device.queue.writeBuffer(this._uniformsBuffer,0,this._uniformsArray);pass.setPipeline(this._computePipeline);pass.setBindGroup(0,this._bindGroups[this._step%2]);pass.dispatchWorkgroups(Math.ceil(this._numParticles/256));++this._step;}
_resetParticles(){for(let i=0;i<this._numParticles;i++){const base=i*8;this._particles[base+0]=Math.random()*2.0-1.0;this._particles[base+1]=Math.random()*2.0-1.0;const angle=Math.random()*Math.PI*2;const speed=0.0005+Math.random()*0.002;this._particles[base+2]=Math.cos(angle)*speed;this._particles[base+3]=Math.sin(angle)*speed;const maxLife=200+Math.random()*200;this._particles[base+4]=maxLife*Math.random();this._particles[base+5]=maxLife;this._particles[base+6]=Math.random();this._particles[base+7]=0.0;}
this._device.queue.writeBuffer(this._particleBuffers[0],0,this._particles);}
_createSpriteTexture(){const size=64;const half=size/2;const data=new Uint8Array(size*size*4);for(let y=0;y<size;y++){for(let x=0;x<size;x++){const dx=x-half,dy=y-half;const dist=Math.sqrt(dx*dx+dy*dy)/half;const alpha=Math.max(0,1.0-dist*dist);const i=(y*size+x)*4;data[i+0]=255;data[i+1]=255;data[i+2]=255;data[i+3]=Math.round(alpha*255);}}
const texture=this._device.createTexture({size:[size,size,1],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST,});this._device.queue.writeTexture({texture},data,{bytesPerRow:size*4},[size,size],);return texture;}
_createBindGroups(pipeline){return[0,1].map(i=>this._device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this._particleBuffers[i]}},{binding:1,resource:{buffer:this._particleBuffers[1-i]}},{binding:2,resource:{buffer:this._uniformsBuffer}},{binding:3,resource:this._spriteTexture.createView()},{binding:4,resource:this._spriteSampler},],}));}}
async function init(){const canvasTag=document.createElement('canvas');canvasTag.id='renderCanvas';document.body.appendChild(canvasTag);const renderer=new Renderer(canvasTag);await renderer.init();renderer._clearColor={r:0.0,g:0.0,b:0.05,a:1.0};const nebula=new NebulaSystemObject(renderer._device,renderer._canvasFormat,'/lib/Shaders/optimized_nebula_particles.wgsl',10000,);const fireworks=new FireworksSystemObject(renderer._device,renderer._canvasFormat,'/lib/Shaders/optimized_fireworks_particles.wgsl',10000,);await renderer.appendSceneObject(nebula);await renderer.appendSceneObject(fireworks);function toNDC(event){const rect=canvasTag.getBoundingClientRect();const x=((event.clientX-rect.left)/rect.width)*2-1;const y=-((event.clientY-rect.top)/rect.height)*2+1;return{x,y};}
canvasTag.addEventListener('click',(e)=>{const{x,y}=toNDC(e);fireworks.setEmitter(x,y);});canvasTag.addEventListener('mousedown',()=>nebula.setAttract(1.0));canvasTag.addEventListener('mouseup',()=>nebula.setAttract(0.0));canvasTag.addEventListener('mousemove',(e)=>{const{x,y}=toNDC(e);nebula.setMousePos(x,y);});const keysDown=new Set();function updateWind(){let wx=0,wy=0;if(keysDown.has('ArrowLeft'))wx-=1;if(keysDown.has('ArrowRight'))wx+=1;if(keysDown.has('ArrowUp'))wy+=1;if(keysDown.has('ArrowDown'))wy-=1;nebula.setWind(wx,wy);}
window.addEventListener('keydown',(e)=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();}
if(e.key==='h'||e.key==='H'){if(hud.style.display==='none'){hud.style.display='';showBtn.style.display='none';}else{hud.style.display='none';showBtn.style.display='';}
return;}
keysDown.add(e.key);updateWind();});window.addEventListener('keyup',(e)=>{keysDown.delete(e.key);updateWind();});const hud=document.createElement('div');hud.id='hud';const titleEl=document.createElement('div');titleEl.className='hud-title';titleEl.textContent='Project 4 — Particle System';hud.appendChild(titleEl);function addKey(parent,label){const btn=document.createElement('span');btn.className='hud-button';btn.textContent=label;parent.appendChild(btn);}
function addRow(parent,labelText,keys){const row=document.createElement('div');row.className='hud-control-row';const lbl=document.createElement('span');lbl.className='hud-label';lbl.textContent=labelText;row.appendChild(lbl);for(const k of keys){addKey(row,k);}
parent.appendChild(row);}
function addSection(title){const sec=document.createElement('div');sec.className='hud-section';const hdr=document.createElement('div');hdr.className='hud-section-header';hdr.textContent=title;sec.appendChild(hdr);hud.appendChild(sec);return sec;}
const fwSec=addSection('FIREWORKS');addRow(fwSec,'Move Burst Origin',['click']);const nebSec=addSection('NEBULA');addRow(nebSec,'Attract Dust',['hold mouse']);addRow(nebSec,'Wind Direction',['←','→','↑','↓']);const info=document.createElement('div');info.className='hud-info';info.textContent='H — Hide / Show HUD';hud.appendChild(info);document.body.appendChild(hud);const showBtn=document.createElement('button');showBtn.id='show-hud-toggle';showBtn.textContent='Show HUD';showBtn.addEventListener('click',()=>{hud.style.display='';showBtn.style.display='none';});document.body.appendChild(showBtn);function renderFrame(){renderer.render();requestAnimationFrame(renderFrame);}
renderFrame();return renderer;}
init().then(ret=>{console.log(ret);}).catch(error=>{const pTag=document.createElement('p');pTag.innerHTML=navigator.userAgent+'<br/>'+error.message;document.body.appendChild(pTag);document.getElementById('renderCanvas').remove();});