class Renderer{constructor(canvas){this._canvas=canvas;this._objects=[];this._clearColor={r:0.95,g:0.92,b:0.88,a:1.0};}
async init(){if(!navigator.gpu){throw Error("WebGPU is not supported in this browser.");}
const adapter=await navigator.gpu.requestAdapter();if(!adapter){throw Error("Couldn't request WebGPU adapter.");}
this._device=await adapter.requestDevice();this._context=this._canvas.getContext("webgpu");this._canvasFormat=navigator.gpu.getPreferredCanvasFormat();this._context.configure({device:this._device,format:this._canvasFormat,});this.resizeCanvas();window.addEventListener('resize',this.resizeCanvas.bind(this));}
resizeCanvas(){const devicePixelRatio=window.devicePixelRatio||1;const width=window.innerWidth*devicePixelRatio;const height=window.innerHeight*devicePixelRatio;this._canvas.width=width;this._canvas.height=height;this._canvas.style.width=`${window.innerWidth}px`;this._canvas.style.height=`${window.innerHeight}px`;this.render();}
async appendSceneObject(obj){await obj.init();this._objects.push(obj);}
renderToSelectedView(outputView){for(const obj of this._objects){obj?.updateGeometry();}
let encoder=this._device.createCommandEncoder();const pass=encoder.beginRenderPass({colorAttachments:[{view:outputView,clearValue:this._clearColor,loadOp:"clear",storeOp:"store",}]});for(const obj of this._objects){obj?.render(pass);}
pass.end();const computePass=encoder.beginComputePass();for(const obj of this._objects){obj?.compute(computePass);}
computePass.end();const commandBuffer=encoder.finish();this._device.queue.submit([commandBuffer]);}
render(){this.renderToSelectedView(this._context.getCurrentTexture().createView());}}
class SceneObject{static _objectCnt=0;constructor(device,canvasFormat,shaderFile){if(this.constructor==SceneObject){throw new Error("Abstract classes can't be instantiated.");}
this._device=device;this._canvasFormat=canvasFormat;this._shaderFile=shaderFile;SceneObject._objectCnt+=1;}
getName(){return this.constructor.name+" "+SceneObject._objectCnt.toString();}
async init(){await this.createGeometry();await this.createShaders();await this.createRenderPipeline();await this.createComputePipeline();}
async createGeometry(){throw new Error("Method 'createGeometry()' must be implemented.");}
updateGeometry(){}
loadShader(filename){return new Promise((resolve,reject)=>{const xhttp=new XMLHttpRequest();xhttp.open("GET",filename);xhttp.setRequestHeader("Cache-Control","no-cache, no-store, max-age=0");xhttp.onload=function(){if(xhttp.readyState===XMLHttpRequest.DONE&&xhttp.status===200){resolve(xhttp.responseText);}
else{reject({status:xhttp.status,statusText:xhttp.statusText});}};xhttp.onerror=function(){reject({status:xhttp.status,statusText:xhttp.statusText});};xhttp.send();});}
async createShaders(){let shaderCode=await this.loadShader(this._shaderFile);this._shaderModule=this._device.createShaderModule({label:" Shader "+this.getName(),code:shaderCode,});}
async createRenderPipeline(){throw new Error("Method 'createRenderPipeline()' must be implemented.");}
render(pass){throw new Error("Method 'render(pass)' must be implemented.");}
async createComputePipeline(){throw new Error("Method 'createComputePipeline()' must be implemented.");}
compute(pass){throw new Error("Method 'compute(pass)' must be implemented.");}}
class ParticleSystemObject extends SceneObject{constructor(device,canvasFormat,shaderFile,numParticles=4096){super(device,canvasFormat,shaderFile);this._numParticles=numParticles;this._step=0;}
async createGeometry(){await this.createParticleGeometry();}
async createParticleGeometry(){this._particles=new Float32Array(this._numParticles*12);this._particleBuffers=[this._device.createBuffer({label:"Particle Buffer 1 "+this.getName(),size:this._particles.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,}),this._device.createBuffer({label:"Particle Buffer 2 "+this.getName(),size:this._particles.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,})];this._device.queue.writeBuffer(this._particleBuffers[0],0,this._particles);this._step=0;this.resetParticles();}
resetParticles(){for(let i=0;i<this._numParticles;++i){this._particles[12*i+0]=(Math.random()*2-1);this._particles[12*i+1]=(Math.random()*2-1);this._particles[12*i+2]=this._particles[12*i+0];this._particles[12*i+3]=this._particles[12*i+1];const velocityX=(Math.random()*2-1)*0.002;const velocityY=(Math.random()*2-1)*0.002;this._particles[12*i+4]=velocityX;this._particles[12*i+5]=velocityY;this._particles[12*i+6]=velocityX;this._particles[12*i+7]=velocityY;let life=Math.floor(128+Math.random()*127);this._particles[12*i+8]=life;this._particles[12*i+9]=life;}
this._step=0;this._device.queue.writeBuffer(this._particleBuffers[this._step%2],0,this._particles);}
updateGeometry(){}
async createShaders(){await super.createShaders()
this._bindGroupLayout=this._device.createBindGroupLayout({label:"Grid Bind Group Layout "+this.getName(),entries:[{binding:0,visibility:GPUShaderStage.VERTEX|GPUShaderStage.COMPUTE,buffer:{type:"read-only-storage"}},{binding:1,visibility:GPUShaderStage.COMPUTE,buffer:{type:"storage"}}]});this._pipelineLayout=this._device.createPipelineLayout({label:"Particles Pipeline Layout",bindGroupLayouts:[this._bindGroupLayout],});}
async createRenderPipeline(){await this.createParticlePipeline();}
async createParticlePipeline(){this._particlePipeline=this._device.createRenderPipeline({label:"Particles Render Pipeline "+this.getName(),layout:this._pipelineLayout,vertex:{module:this._shaderModule,entryPoint:"vertexMain",},fragment:{module:this._shaderModule,entryPoint:"fragmentMain",targets:[{format:this._canvasFormat}]},primitives:{topology:'line-strip'}});this._bindGroups=[this._device.createBindGroup({layout:this._particlePipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this._particleBuffers[0]}},{binding:1,resource:{buffer:this._particleBuffers[1]}}],}),this._device.createBindGroup({layout:this._particlePipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this._particleBuffers[1]}},{binding:1,resource:{buffer:this._particleBuffers[0]}}],})];}
render(pass){pass.setPipeline(this._particlePipeline);pass.setBindGroup(0,this._bindGroups[this._step%2]);pass.draw(128,this._numParticles);}
async createComputePipeline(){this._computePipeline=this._device.createComputePipeline({label:"Particles Compute Pipeline "+this.getName(),layout:this._pipelineLayout,compute:{module:this._shaderModule,entryPoint:"computeMain",}});}
compute(pass){pass.setPipeline(this._computePipeline);pass.setBindGroup(0,this._bindGroups[this._step%2]);pass.dispatchWorkgroups(Math.ceil(this._numParticles/256));++this._step}};class FireParticleSystemObject extends SceneObject{constructor(device,canvasFormat,shaderFile,numParticles=4096){super(device,canvasFormat,shaderFile);this._numParticles=numParticles;this._step=0;}
async createGeometry(){await this.createParticleGeometry();}
async createParticleGeometry(){this._particles=new Float32Array(this._numParticles*6);this._particleBuffers=[this._device.createBuffer({label:"Particle Buffer 1 "+this.getName(),size:this._particles.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,}),this._device.createBuffer({label:"Particle Buffer 2 "+this.getName(),size:this._particles.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,})];this._device.queue.writeBuffer(this._particleBuffers[0],0,this._particles);this._step=0;this._timeArray=new Float32Array(1);this._timeBuffer=this._device.createBuffer({label:"Time Buffer "+this.getName(),size:this._timeArray.byteLength,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST,});this.resetParticles();}
resetParticles(){const baseX=0.0;const baseY=-0.8;for(let i=0;i<this._numParticles;++i){const idx=6*i;this._particles[idx+0]=baseX;this._particles[idx+1]=baseY;const vx=(Math.random()*2-1)*0.001;const vy=0.01+Math.random()*0.01;this._particles[idx+2]=vx;this._particles[idx+3]=vy;const life=128+Math.random()*127;this._particles[idx+4]=life;this._particles[idx+5]=1.0;}
this._step=0;this._device.queue.writeBuffer(this._particleBuffers[this._step%2],0,this._particles);}
updateGeometry(){}
async createShaders(){await super.createShaders()
this._bindGroupLayout=this._device.createBindGroupLayout({label:"Grid Bind Group Layout "+this.getName(),entries:[{binding:0,visibility:GPUShaderStage.VERTEX|GPUShaderStage.COMPUTE,buffer:{type:"read-only-storage"}},{binding:1,visibility:GPUShaderStage.COMPUTE,buffer:{type:"storage"}},{binding:2,visibility:GPUShaderStage.COMPUTE,buffer:{type:"uniform"}}]});this._pipelineLayout=this._device.createPipelineLayout({label:"Particles Pipeline Layout",bindGroupLayouts:[this._bindGroupLayout],});}
async createRenderPipeline(){await this.createParticlePipeline();}
async createParticlePipeline(){this._particlePipeline=this._device.createRenderPipeline({label:"Particles Render Pipeline "+this.getName(),layout:this._pipelineLayout,vertex:{module:this._shaderModule,entryPoint:"vertexMain",},fragment:{module:this._shaderModule,entryPoint:"fragmentMain",targets:[{format:this._canvasFormat,blend:{color:{srcFactor:'one',dstFactor:'one-minus-src-alpha',operation:'add',},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha',operation:'add',},},}],},primitives:{topology:'line-strip'}});this._bindGroups=[this._device.createBindGroup({layout:this._particlePipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this._particleBuffers[0]}},{binding:1,resource:{buffer:this._particleBuffers[1]}},{binding:2,resource:{buffer:this._timeBuffer}}],}),this._device.createBindGroup({layout:this._particlePipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this._particleBuffers[1]}},{binding:1,resource:{buffer:this._particleBuffers[0]}},{binding:2,resource:{buffer:this._timeBuffer}}],})];}
render(pass){pass.setPipeline(this._particlePipeline);pass.setBindGroup(0,this._bindGroups[this._step%2]);pass.draw(128,this._numParticles);}
async createComputePipeline(){this._computePipeline=this._device.createComputePipeline({label:"Particles Compute Pipeline "+this.getName(),layout:this._pipelineLayout,compute:{module:this._shaderModule,entryPoint:"computeMain",}});}
compute(pass){this._timeArray[0]=performance.now()/1000.0;this._device.queue.writeBuffer(this._timeBuffer,0,this._timeArray);pass.setPipeline(this._computePipeline);pass.setBindGroup(0,this._bindGroups[this._step%2]);pass.dispatchWorkgroups(Math.ceil(this._numParticles/256));++this._step}}
async function init(){const canvasTag=document.createElement('canvas');canvasTag.id="renderCanvas";document.body.appendChild(canvasTag);const renderer=new Renderer(canvasTag);await renderer.init();var particles=new ParticleSystemObject(renderer._device,renderer._canvasFormat,"/lib/Shaders/optimized_gravity_particles.wgsl");var fireParticles=new FireParticleSystemObject(renderer._device,renderer._canvasFormat,"/lib/Shaders/optimized_fire_particles.wgsl");await renderer.appendSceneObject(particles);await renderer.appendSceneObject(fireParticles);function renderFrame(){renderer.render();requestAnimationFrame(renderFrame);}
renderFrame();return renderer;}
init().then(ret=>{console.log(ret);}).catch(error=>{const pTag=document.createElement('p');pTag.innerHTML=navigator.userAgent+"</br>"+error.message;document.body.appendChild(pTag);document.getElementById("renderCanvas").remove();});