class Renderer{constructor(canvas){this._canvas=canvas;this._objects=[];this._clearColor={r:0.95,g:0.92,b:0.88,a:1.0};}
async init(){if(!navigator.gpu){throw Error("WebGPU is not supported in this browser.");}
const adapter=await navigator.gpu.requestAdapter();if(!adapter){throw Error("Couldn't request WebGPU adapter.");}
this._device=await adapter.requestDevice();this._context=this._canvas.getContext("webgpu");this._canvasFormat=navigator.gpu.getPreferredCanvasFormat();this._context.configure({device:this._device,format:this._canvasFormat,});this.resizeCanvas();window.addEventListener('resize',this.resizeCanvas.bind(this));}
resizeCanvas(){const devicePixelRatio=window.devicePixelRatio||1;const width=window.innerWidth*devicePixelRatio;const height=window.innerHeight*devicePixelRatio;this._canvas.width=width;this._canvas.height=height;this._canvas.style.width=`${window.innerWidth}px`;this._canvas.style.height=`${window.innerHeight}px`;this.render();}
async appendSceneObject(obj){await obj.init();this._objects.push(obj);}
renderToSelectedView(outputView){for(const obj of this._objects){obj?.updateGeometry();}
let encoder=this._device.createCommandEncoder();const pass=encoder.beginRenderPass({colorAttachments:[{view:outputView,clearValue:this._clearColor,loadOp:"clear",storeOp:"store",}]});for(const obj of this._objects){obj?.render(pass);}
pass.end();const computePass=encoder.beginComputePass();for(const obj of this._objects){obj?.compute(computePass);}
computePass.end();const commandBuffer=encoder.finish();this._device.queue.submit([commandBuffer]);}
render(){this.renderToSelectedView(this._context.getCurrentTexture().createView());}}
class SceneObject{static _objectCnt=0;constructor(device,canvasFormat,shaderFile){if(this.constructor==SceneObject){throw new Error("Abstract classes can't be instantiated.");}
this._device=device;this._canvasFormat=canvasFormat;this._shaderFile=shaderFile;SceneObject._objectCnt+=1;}
getName(){return this.constructor.name+" "+SceneObject._objectCnt.toString();}
async init(){await this.createGeometry();await this.createShaders();await this.createRenderPipeline();await this.createComputePipeline();}
async createGeometry(){throw new Error("Method 'createGeometry()' must be implemented.");}
updateGeometry(){}
loadShader(filename){return new Promise((resolve,reject)=>{const xhttp=new XMLHttpRequest();xhttp.open("GET",filename);xhttp.setRequestHeader("Cache-Control","no-cache, no-store, max-age=0");xhttp.onload=function(){if(xhttp.readyState===XMLHttpRequest.DONE&&xhttp.status===200){resolve(xhttp.responseText);}
else{reject({status:xhttp.status,statusText:xhttp.statusText});}};xhttp.onerror=function(){reject({status:xhttp.status,statusText:xhttp.statusText});};xhttp.send();});}
async createShaders(){let shaderCode=await this.loadShader(this._shaderFile);this._shaderModule=this._device.createShaderModule({label:" Shader "+this.getName(),code:shaderCode,});}
async createRenderPipeline(){throw new Error("Method 'createRenderPipeline()' must be implemented.");}
render(pass){throw new Error("Method 'render(pass)' must be implemented.");}
async createComputePipeline(){throw new Error("Method 'createComputePipeline()' must be implemented.");}
compute(pass){throw new Error("Method 'compute(pass)' must be implemented.");}}
class MassSpringSystemObject extends SceneObject{constructor(device,canvasFormat,shaderFile,numParticles=16){super(device,canvasFormat,shaderFile);this._size=numParticles;this._numParticles=this._size*this._size;this._numSprings=[this._size*Math.ceil((this._size-1)/2),this._size*Math.floor((this._size-1)/2),this._size*Math.ceil((this._size-1)/2),this._size*Math.floor((this._size-1)/2)];this._step=0;}
async createGeometry(){await this.createParticleGeometry();await this.createSpringGeometry();}
async createParticleGeometry(){this._particles=new Float32Array(this._numParticles*8);this._particleBuffers=[this._device.createBuffer({label:"Particles Buffer 1 "+this.getName(),size:this._particles.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,}),this._device.createBuffer({label:"Particles Buffer 2 "+this.getName(),size:this._particles.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,})];this.resetParticles();}
async createSpringGeometry(){this._springs=[new Float32Array(this._numSprings[0]*4),new Float32Array(this._numSprings[1]*4),new Float32Array(this._numSprings[2]*4),new Float32Array(this._numSprings[3]*4)];this._springBuffer=[this._device.createBuffer({label:"Spring Buffer 1 "+this.getName(),size:this._springs[0].byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,}),this._device.createBuffer({label:"Spring Buffer 2 "+this.getName(),size:this._springs[1].byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,}),this._device.createBuffer({label:"Spring Buffer 3 "+this.getName(),size:this._springs[2].byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,}),this._device.createBuffer({label:"Spring Buffer 4 "+this.getName(),size:this._springs[3].byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,})]
this.resetSprings();}
resetParticles(){let edgeLength=0.7;let delta=edgeLength/this._size;for(let j=0;j<this._size;++j)for(let i=0;i<this._size;++i){let idx=j*this._size+i;this._particles[8*idx+0]=-0.25+delta*i;this._particles[8*idx+1]=0.5-delta*j;this._particles[8*idx+2]=0;this._particles[8*idx+3]=0;this._particles[8*idx+4]=0;this._particles[8*idx+5]=0;this._particles[8*idx+6]=0.0001*this._numParticles;this._particles[8*idx+7]=(j==0)?1:0;}
this._step=0;this._device.queue.writeBuffer(this._particleBuffers[this._step%2],0,this._particles);}
resetSprings(){var mapped=new Map();for(let i=0;i<this._numParticles;++i){mapped[i]=new Set();mapped[i].add(i);}
let edgeLength=0.7;let delta=edgeLength/this._size;let stiffness=4;let offset=this._size*(this._size-1);let ysize=Math.ceil((this._size-1)/2);for(let j=0;j<this._size;++j)for(let i=0;i<ysize;++i){let idx=j*ysize+i;this._springs[0][4*idx+0]=j*this._size+i*2;this._springs[0][4*idx+1]=j*this._size+i*2+1;this._springs[0][4*idx+2]=delta;this._springs[0][4*idx+3]=stiffness;this._springs[2][4*idx+0]=2*i*this._size+j;this._springs[2][4*idx+1]=(2*i+1)*this._size+j;this._springs[2][4*idx+2]=delta;this._springs[2][4*idx+3]=stiffness;}
ysize=Math.floor((this._size-1)/2);for(let j=0;j<this._size;++j)for(let i=0;i<ysize;++i){let idx=j*ysize+i;this._springs[1][4*idx+0]=j*this._size+i*2+1;this._springs[1][4*idx+1]=j*this._size+i*2+2;this._springs[1][4*idx+2]=delta;this._springs[1][4*idx+3]=stiffness;this._springs[3][4*idx+0]=(2*i+1)*this._size+j;this._springs[3][4*idx+1]=(2*i+2)*this._size+j;this._springs[3][4*idx+2]=delta;this._springs[3][4*idx+3]=stiffness;}
this._step=0;for(let i=0;i<4;++i){this._device.queue.writeBuffer(this._springBuffer[i],0,this._springs[i]);}}
updateGeometry(){}
async createShaders(){await super.createShaders();this._bindGroupLayout=this._device.createBindGroupLayout({label:"Grid Bind Group Layout "+this.getName(),entries:[{binding:0,visibility:GPUShaderStage.VERTEX|GPUShaderStage.COMPUTE,buffer:{type:"read-only-storage"}},{binding:1,visibility:GPUShaderStage.COMPUTE,buffer:{type:"storage"}},{binding:2,visibility:GPUShaderStage.VERTEX|GPUShaderStage.COMPUTE,buffer:{type:"read-only-storage"}}]});this._pipelineLayout=this._device.createPipelineLayout({label:"Particles Pipeline Layout",bindGroupLayouts:[this._bindGroupLayout],});}
async createRenderPipeline(){await this.createParticlePipeline();await this.createSpringPipeline();}
async createParticlePipeline(){this._particlePipeline=this._device.createRenderPipeline({label:"Particles Render Pipeline "+this.getName(),layout:this._pipelineLayout,vertex:{module:this._shaderModule,entryPoint:"vertexMain",},fragment:{module:this._shaderModule,entryPoint:"fragmentMain",targets:[{format:this._canvasFormat}]},primitives:{typology:'line-strip'}});this._bindGroups=[];for(let i=0;i<4;++i){this._bindGroups.push([this._device.createBindGroup({layout:this._particlePipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this._particleBuffers[0]}},{binding:1,resource:{buffer:this._particleBuffers[1]}},{binding:2,resource:{buffer:this._springBuffer[i]}}],}),this._device.createBindGroup({layout:this._particlePipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this._particleBuffers[1]}},{binding:1,resource:{buffer:this._particleBuffers[0]}},{binding:2,resource:{buffer:this._springBuffer[i]}}],})]);}}
async createSpringPipeline(){this._springPipeline=this._device.createRenderPipeline({label:"Spring Render Pipeline "+this.getName(),layout:this._pipelineLayout,vertex:{module:this._shaderModule,entryPoint:"vertexSpringMain",},fragment:{module:this._shaderModule,entryPoint:"fragmentSpringMain",targets:[{format:this._canvasFormat}]},primitives:{typology:'line-list'}});}
render(pass){pass.setPipeline(this._springPipeline);for(let i=0;i<4;++i)if(this._numSprings[i]){pass.setBindGroup(0,this._bindGroups[i][this._step%2]);pass.draw(12,this._numSprings[i]);}
pass.setPipeline(this._particlePipeline);pass.setBindGroup(0,this._bindGroups[0][this._step%2]);pass.draw(128,this._numParticles);}
async createComputePipeline(){this._computePipeline=this._device.createComputePipeline({label:"Particles Compute Pipeline "+this.getName(),layout:this._pipelineLayout,compute:{module:this._shaderModule,entryPoint:"computeMain",}});this._updatePipeline=this._device.createComputePipeline({label:"Particles Update Pipeline "+this.getName(),layout:this._pipelineLayout,compute:{module:this._shaderModule,entryPoint:"updateMain",}});}
compute(pass){for(let i=0;i<4;++i)if(this._numSprings[i]){pass.setPipeline(this._computePipeline);pass.setBindGroup(0,this._bindGroups[i][this._step%2]);pass.dispatchWorkgroups(Math.ceil(this._numSprings[i]/256));}
pass.setPipeline(this._updatePipeline);pass.setBindGroup(0,this._bindGroups[0][this._step%2]);pass.dispatchWorkgroups(Math.ceil(this._numParticles/256));++this._step}}
async function init(){const canvasTag=document.createElement('canvas');canvasTag.id="renderCanvas";document.body.appendChild(canvasTag);const renderer=new Renderer(canvasTag);await renderer.init();var massSprings=new MassSpringSystemObject(renderer._device,renderer._canvasFormat,"/lib/Shaders/optimized_massspring.wgsl");await renderer.appendSceneObject(massSprings);function renderFrame(){renderer.render();requestAnimationFrame(renderFrame);}
renderFrame();return renderer;}
init().then(ret=>{console.log(ret);}).catch(error=>{const pTag=document.createElement('p');pTag.innerHTML=navigator.userAgent+"</br>"+error.message;document.body.appendChild(pTag);document.getElementById("renderCanvas").remove();});